import type {
  SharePersona,
} from '@baichile/api-contract';
import type { ShareInviteDoc, WalletTransactionDoc } from './models';

const RETIRED_COPY_MARKER = '\u6a21\u62df';
const LEGACY_ORDER_PAYMENT_DESCRIPTION = `${RETIRED_COPY_MARKER}订单扣款（虚拟余额）`;

// These are the exact system-owned strings previously generated by this
// service. Deliberately avoid a generic text replacement: catalog text and
// administrator-entered descriptions must remain untouched.
const LEGACY_SHARE_COPY = new Map<string, string>([
  [`${RETIRED_COPY_MARKER}热量忍者`, '热量忍者'],
  [`${RETIRED_COPY_MARKER}热量刚到门口，你已经完成了整桌推演。`, '热量刚到门口，你已经完成了整桌推演。'],
  [`对${RETIRED_COPY_MARKER}热量极其敏锐，最享受在虚拟点单里研究一整桌。`, '对热量极其敏锐，最享受在虚拟点单里研究一整桌。'],
  [`看看你的${RETIRED_COPY_MARKER}热量人格`, '看看你的热量人格'],
  [`${RETIRED_COPY_MARKER}订单金额审计官`, '订单金额审计官'],
  [`每一笔${RETIRED_COPY_MARKER}订单金额，都要算得有凭有据。`, '每一笔订单金额，都要算得有凭有据。'],
  [`你对价格有天然雷达，享受看着累计${RETIRED_COPY_MARKER}订单金额稳定上涨。`, '你对价格有天然雷达，享受看着累计订单金额稳定上涨。'],
  [`测测你的${RETIRED_COPY_MARKER}订单金额人格`, '测测你的订单金额人格'],
  [`我的这顿白吃人格是 CALN · ${RETIRED_COPY_MARKER}热量忍者`, '我的这顿白吃人格是 CALN · 热量忍者'],
  [`我的这顿白吃人格是 BUDG · ${RETIRED_COPY_MARKER}订单金额审计官`, '我的这顿白吃人格是 BUDG · 订单金额审计官'],
]);

export function sanitizeWalletTransactionCopy(
  row: WalletTransactionDoc,
): WalletTransactionDoc {
  return {
    ...row,
    description: row.description === LEGACY_ORDER_PAYMENT_DESCRIPTION
      ? '订单扣款（虚拟余额）'
      : row.description,
  };
}

function sanitizeSharePersonaCopy(value: SharePersona): SharePersona {
  return {
    ...value,
    name: LEGACY_SHARE_COPY.get(value.name) ?? value.name,
    verdict: LEGACY_SHARE_COPY.get(value.verdict) ?? value.verdict,
    description: LEGACY_SHARE_COPY.get(value.description) ?? value.description,
    callToAction: LEGACY_SHARE_COPY.get(value.callToAction) ?? value.callToAction,
  };
}

export function sanitizeShareInviteCopy(row: ShareInviteDoc): ShareInviteDoc {
  const snapshot = row.snapshot;
  return {
    ...row,
    title: LEGACY_SHARE_COPY.get(row.title) ?? row.title,
    snapshot: {
      ...snapshot,
      ...(snapshot.persona
        ? { persona: sanitizeSharePersonaCopy(snapshot.persona) }
        : {}),
    },
  };
}
