import type { StoreDetail } from '@baichile/api-contract';
import { estimateCalories } from './calorie-estimates';

const STORE_ID = 'kamii-buffet-shanlan';

/*
 * Menu names and categories were extracted from the public menu at
 * https://www.kamii.com.cn/Dishes and its linked category pages.
 * The official image endpoints returned empty responses on 2026-07-15, so
 * each category uses a clearly non-branded generated food-photo fallback.
 */
const items = [
  ['综合刺身', '刺身', 'sashimi'],
  ['八爪魚刺身&鰤魚刺身', '刺身', 'sashimi'],
  ['海胆', '刺身', 'sashimi'],
  ['三文鱼刺身', '刺身', 'sashimi'],
  ['希鲮鱼刺身', '刺身', 'sashimi'],
  ['北极贝刺身', '刺身', 'sashimi'],
  ['鲷鱼刺身&酱白螺', '刺身', 'sashimi'],
  ['金枪鱼刺身', '刺身', 'sashimi'],
  ['帆立贝刺身', '刺身', 'sashimi'],
  ['甜虾刺身&冰镇旭蟹', '刺身', 'sashimi'],
  ['矶煮鲍鱼', '刺身', 'sashimi'],
  ['泰式青口贝', '刺身', 'sashimi'],
  ['法棍鱼籽', '珍味', 'delicacies'],
  ['飛魚籽&三文魚籽', '珍味', 'delicacies'],
  ['一品海鲜塔', '珍味', 'delicacies'],
  ['和风冰山蚌', '珍味', 'delicacies'],
  ['明虾春卷', '珍味', 'delicacies'],
  ['鮟鱇鱼肝柚子醋', '珍味', 'delicacies'],
  ['和风熏牛肉', '珍味', 'delicacies'],
  ['椒麻魚皮&中華海草&風味干貝裙&芥末章魚', '珍味', 'delicacies'],
  ['雪蟹醋凍', '珍味', 'delicacies'],
  ['納豆&一品丹波黑豆&枝豆', '珍味', 'delicacies'],
  ['水果色拉&紅酒番茄&情人果', '珍味', 'delicacies'],
  ['和牛肥肝手握&三文魚芝士手握', '寿司', 'sushi'],
  ['蟹籽手卷', '寿司', 'sushi'],
  ['鹅肝鱼籽手握', '寿司', 'sushi'],
  ['明蝦芝士手握&鰻魚手握', '寿司', 'sushi'],
  ['明蝦蔬菜手卷', '寿司', 'sushi'],
  ['豆皮壽司', '寿司', 'sushi'],
  ['老虎卷&毛毛蟲卷&彩虹卷', '寿司', 'sushi'],
  ['蟹钳', '扬物', 'fried'],
  ['韓式辣年糕條', '扬物', 'fried'],
  ['熔岩蝦球&藍帶豬排', '扬物', 'fried'],
  ['鮮蝦天婦羅', '扬物', 'fried'],
  ['星鰻天婦羅', '扬物', 'fried'],
  ['炸河豚', '扬物', 'fried'],
  ['炸薯條&鐵板波羅&酥炸香菇&野菜天婦羅', '扬物', 'fried'],
  ['芝士焗蝦&鹽烤明蝦', '炉端烧', 'robata'],
  ['酱烧牛肋条', '炉端烧', 'robata'],
  ['奶酪焗蟹宝', '炉端烧', 'robata'],
  ['雞皮串&七味雞軟骨', '炉端烧', 'robata'],
  ['金槍魚下巴', '炉端烧', 'robata'],
  ['烤榴槤', '炉端烧', 'robata'],
  ['上井西京燒&蒲燒鰻魚', '炉端烧', 'robata'],
  ['蒜蓉扇貝&焗烤青口被&元貝吉士燒&蒜蓉生蠔', '炉端烧', 'robata'],
  ['味淋烤魚翅', '炉端烧', 'robata'],
  ['鹽烤多春魚&鹽烤秋刀魚&鹽烤冰魚', '炉端烧', 'robata'],
  ['鹽烤鮭魚頭', '炉端烧', 'robata'],
  ['鹽烤青花魚&鹽烤銀杏&奧爾良烤翅', '炉端烧', 'robata'],
  ['鹽烤午仔魚&香酥帶魚', '炉端烧', 'robata'],
  ['铁板牛肉', '铁板烧', 'teppanyaki'],
  ['XO醬鐵板海鮮', '铁板烧', 'teppanyaki'],
  ['法式肥肝', '铁板烧', 'teppanyaki'],
  ['厚燒牛舌&蔥燒牛舌', '铁板烧', 'teppanyaki'],
  ['辣炒鮮蛤&燈籠找雞&黑松露炒時蔬', '铁板烧', 'teppanyaki'],
  ['清酒柏明蝦', '铁板烧', 'teppanyaki'],
  ['鐵板牛舌', '铁板烧', 'teppanyaki'],
  ['海鲜蒸蛋&肥肝蒸蛋', '煮物', 'simmered'],
  ['海螺酱烧', '煮物', 'simmered'],
  ['石鍋牛肉', '煮物', 'simmered'],
  ['寿喜锅', '锅物', 'hotpot'],
  ['辣牛肉鍋', '锅物', 'hotpot'],
  ['海鮮鍋', '锅物', 'hotpot'],
  ['特上選牛肉', '火锅肉品', 'hotpot-meat'],
  ['伊比利亞黑毛豬&黑毛牛卡盧比&上選牛肉', '火锅肉品', 'hotpot-meat'],
  ['海鮮土瓶蒸', '汤品', 'soup'],
  ['味增湯', '汤品', 'soup'],
  ['手作海胆水饺', '主食', 'staple'],
  ['海鮮炒烏冬', '主食', 'staple'],
  ['三文魚炒飯&鰻魚飯', '主食', 'staple'],
  ['北海道冰淇淋', '甜品', 'dessert'],
  ['風味大福', '甜品', 'dessert'],
  ['提拉米蘇', '甜品', 'dessert'],
  ['奶酪&焦糖布丁', '甜品', 'dessert'],
  ['星空雪燕', '甜品', 'dessert'],
  ['港式鴛鴦奶茶', '饮品', 'drink'],
  ['桂圓紅棗茶', '饮品', 'drink'],
  ['芒果汁&西瓜汁', '饮品', 'drink'],
  ['玫瑰花茶', '饮品', 'drink'],
  ['木瓜牛奶&可爾必思&黑糖珍珠鮮奶', '饮品', 'drink'],
  ['楊枝甘露', '饮品', 'drink'],
  ['清酒', '饮品', 'drink'],
] as const;

const imageBySubCategory = {
  sashimi: 'km-fallback-sashimi.jpg',
  delicacies: 'km-fallback-delicacies.jpg',
  sushi: 'km-fallback-sushi.jpg',
  fried: 'km-fallback-fried.jpg',
  robata: 'km-fallback-robata.jpg',
  teppanyaki: 'km-fallback-teppanyaki.jpg',
  simmered: 'km-fallback-simmered.jpg',
  hotpot: 'km-fallback-hotpot.jpg',
  'hotpot-meat': 'km-fallback-hotpot-meat.jpg',
  soup: 'km-fallback-soup.jpg',
  staple: 'km-fallback-staple.jpg',
  dessert: 'km-fallback-dessert.jpg',
  drink: 'km-fallback-drink.jpg',
} as const;

export const kamiiBuffetStore: StoreDetail = {
  id: STORE_ID,
  name: '山岚日料自助',
  categoryId: 'ct-western',
  description: '日料自助菜单，菜品均包含在自助餐内。',
  coverUrl: '/static/kamii-buffet-img/km-fallback-sashimi.jpg',
  tags: ['日料自助', '刺身寿司', '铁板料理'],
  deliveryFeeCents: 0,
  packingFeeCents: 0,
  minimumOrderCents: 0,
  virtualDeliveryMinutes: 30,
  monthlySales: 0,
  distanceKm: 1.8,
  rating: 4.7,
  recentViewers: 186,
  systemHeat: 93,
  sourceType: 'derived',
  subCategories: [
    { id: 'sashimi', name: '刺身' },
    { id: 'delicacies', name: '珍味' },
    { id: 'sushi', name: '寿司' },
    { id: 'fried', name: '扬物' },
    { id: 'robata', name: '炉端烧' },
    { id: 'teppanyaki', name: '铁板烧' },
    { id: 'simmered', name: '煮物' },
    { id: 'hotpot', name: '锅物' },
    { id: 'hotpot-meat', name: '火锅肉品' },
    { id: 'soup', name: '汤品' },
    { id: 'staple', name: '主食' },
    { id: 'dessert', name: '甜品' },
    { id: 'drink', name: '饮品' },
  ],
  menu: items.map(([name, subtitle, subCategoryId], index) => {
    const calories = estimateCalories(name, 'japanese');
    const itemNumber = String(index + 1).padStart(3, '0');
    return {
      id: `${STORE_ID}-item-${itemNumber}`,
      storeId: STORE_ID,
      categoryId: 'ct-western',
      subCategoryId,
      name,
      subtitle,
      imageUrl: `/static/kamii-buffet-img/${imageBySubCategory[subCategoryId]}`,
      // The source menu has no a-la-carte prices; dishes are included in the buffet.
      basePriceCents: 0,
      ...calories,
      monthlySales: 0,
      specGroups: [],
      sourceType: 'derived' as const,
    };
  }),
};
