import type { Category, MenuItem, MenuSubCategory, StoreDetail } from '@baichile/api-contract';
import type { SpecGroup } from '@baichile/domain';
import { estimateCalories, withCalorieDeltas } from './calorie-estimates';
import { choutuanCategories, choutuanStores } from './catalog.choutuan';
import { japaneseBuffetStore } from './catalog.japanese-buffet';
import { kamiiBuffetStore } from './catalog.kamii-buffet';

export { japaneseBuffetStore } from './catalog.japanese-buffet';
export { kamiiBuffetStore } from './catalog.kamii-buffet';
import { transformStoreName } from './name-transform';

/* ═══════════════════════════════════════════════
   Categories
   ═══════════════════════════════════════════════ */
const baseCategories: Category[] = [
  ['bbq', '烧烤', 'bbq'], ['fried', '炸鸡', 'friedChicken'], ['burger', '汉堡', 'burger'],
  ['noodles', '粉面', 'noodles'], ['rice', '盖饭', 'rice'], ['tea', '奶茶', 'milkTea'],
  ['dessert', '甜品', 'dessert'], ['night', '夜宵', 'lateNight'],
].map(([id, name, icon]) => ({ id, name, icon }));

export const categories: Category[] = [
  ...choutuanCategories,
];

/* ═══════════════════════════════════════════════
   Helpers
   ═══════════════════════════════════════════════ */
interface RawItem {
  name: string;
  subtitle?: string;
  price: number;            // 元
  specs?: Partial<SpecGroup>[];
}
interface RawStore {
  name: string;
  categoryId: string;
  description: string;
  tags: string[];
  deliveryFee: number;      // 元
  packingFee: number;
  minOrder: number;
  deliveryMin: number;
  monthlySales: number;
  distanceKm: number;
  rating: number;
  items: RawItem[];
}

const yuan = (n: number) => Math.round(n * 100);

function sizeSpec(id: string): SpecGroup {
  return {
    id: `${id}-size`, name: '份量', required: true, minSelect: 1, maxSelect: 1,
    options: [
      { id: `${id}-std`, name: '标准份', priceDeltaCents: 0, calorieDeltaKcal: 0, isDefault: true },
      { id: `${id}-lg`, name: '大份', priceDeltaCents: 500, calorieDeltaKcal: 0 },
    ],
  };
}
function spiceSpec(id: string, levels: string[] = ['微辣', '中辣', '特辣']): SpecGroup {
  return {
    id: `${id}-spice`, name: '辣度', required: false, minSelect: 0, maxSelect: 1,
    options: levels.map((name, i) => ({
      id: `${id}-spice-${i}`, name, priceDeltaCents: 0, calorieDeltaKcal: 0,
    })),
  };
}
function sweetSpec(id: string, levels: string[] = ['正常糖', '七分糖', '半糖', '不加糖']): SpecGroup {
  return {
    id: `${id}-sweet`, name: '甜度', required: false, minSelect: 0, maxSelect: 1,
    options: levels.map((name, i) => ({
      id: `${id}-sweet-${i}`, name, priceDeltaCents: 0, calorieDeltaKcal: 0,
    })),
  };
}
function tempSpec(id: string): SpecGroup {
  return {
    id: `${id}-temp`, name: '温度', required: false, minSelect: 0, maxSelect: 1,
    options: [
      { id: `${id}-hot`, name: '热', priceDeltaCents: 0, calorieDeltaKcal: 0 },
      { id: `${id}-ice`, name: '冰', priceDeltaCents: 0, calorieDeltaKcal: 0 },
      { id: `${id}-warm`, name: '温', priceDeltaCents: 0, calorieDeltaKcal: 0 },
    ],
  };
}
function drinkSizeSpec(id: string): SpecGroup {
  return {
    id: `${id}-size`, name: '杯型', required: true, minSelect: 1, maxSelect: 1,
    options: [
      { id: `${id}-med`, name: '中杯', priceDeltaCents: 0, calorieDeltaKcal: 0, isDefault: true },
      { id: `${id}-lg`, name: '大杯', priceDeltaCents: 300, calorieDeltaKcal: 0 },
      { id: `${id}-xl`, name: '超大杯', priceDeltaCents: 500, calorieDeltaKcal: 0 },
    ],
  };
}

/* ═══════════════════════════════════════════════
   Sub-category templates per platform category
   ═══════════════════════════════════════════════ */
interface SubCategoryTemplate {
  id: string;
  name: string;
  keywords: string[];
}
const SUB_CATEGORY_MAP: Record<string, SubCategoryTemplate[]> = {
  bbq: [
    { id: 'skewer', name: '烤串', keywords: ['串', '羊肉串', '牛肉串', '鸡翅中', '脆骨', '鸡心', '板筋', '鸡皮', '实蛋', '心管', '小腰', '牛板筋', '烤翅', '猪五花', '羊排串', '烤五花', '牛胸口'] },
    { id: 'seafood', name: '海鲜', keywords: ['生蚝', '扇贝', '花蛤', '大虾', '虾', '明太鱼'] },
    { id: 'poultry', name: '禽类', keywords: ['猪蹄', '全翅', '鸡腿', '鸡翅根', '鸡脆骨', '鸡爪', '鸡排'] },
    { id: 'veg', name: '蔬菜/锡纸', keywords: ['茄子', '韭菜', '金针菇', '娃娃菜', '大蒜', '玉米', '秋刀', '枝豆', '银杏', '辣椒', '茄子', '年糕', '面包片', '馒头', '冷面', '饭团', '菠萝', '香蕉'] },
    { id: 'sides', name: '小菜/汤', keywords: ['毛豆', '花生', '凉菜', '拍黄瓜', '拌', '皮蛋', '木耳', '沙拉', '大拉皮', '疙瘩汤', '味噌汤', '酸辣汤', '冰粉', '玉米浓汤', '酥肉', '卤鸡'] },
    { id: 'staple', name: '主食', keywords: ['炒饭', '拌饭', '石锅', '方便面', '烤肠', '冒菜', '酥肉', '卤鸡', '鸡', '牛', '羊', '和牛', '牛舌', '猪颈', '肩肉', '腿肉', '烤鱼', '蒜香烤', '酸菜烤', '豆豉烤', '麻辣烤'] },
  ],
  fried: [
    { id: 'chicken', name: '炸鸡', keywords: ['炸鸡', '整只', '半只', '鸡块', '鸡排', '鸡翅', '鸡腿', '鸡柳', '手枪腿', '鸡米花', '盐酥鸡'] },
    { id: 'korean', name: '韩式', keywords: ['甜辣', '酱油蒜香', '芝士炸鸡', '雪花炸鸡', '辣炒年糕', '鱼饼', '紫菜包饭', '腌萝卜'] },
    { id: 'sides', name: '小食', keywords: ['薯条', '洋葱圈', '芝士球', '地瓜', '花枝丸', '甜不辣', '米血', '鱿鱼', '烤肠', '红豆派', '比司吉', '鸡肉三明治', '鸡肉卷', '年糕', '披萨'] },
    { id: 'other', name: '其他', keywords: [] },
  ],
  burger: [
    { id: 'burger', name: '汉堡', keywords: ['堡', '皇堡', 'ShackBurger', 'SmokeShack', 'Shack Stack', '汉堡', '鳕鱼'] },
    { id: 'chicken', name: '鸡肉类', keywords: ['鸡翅', '鸡块', '鸡柳', '鸡肉卷', '原味鸡', '香骨鸡', '霸王鸡条', '嫩牛五方'] },
    { id: 'sides', name: '小食/甜品', keywords: ['薯条', '洋葱圈', '圣代', '冰淇淋', '蛋挞', '土豆泥', '派', '甜筒', '麦旋风', '奶昔', '热狗', '圆筒'] },
    { id: 'other', name: '其他', keywords: [] },
  ],
  noodles: [
    { id: 'noodle', name: '面食', keywords: ['面', '抄手', '汤圆', '酸辣粉'] },
    { id: 'rice_noodle', name: '粉类', keywords: ['粉', '米线', '渔粉', '冒粉'] },
    { id: 'snacks', name: '小吃/加料', keywords: ['煎饺', '炸猪排', '炒饭', '唐扬', '酿皮', '甜醅', '灰豆', '卤蛋', '卤豆腐', '臭豆腐', '糖油粑粑', '冰粉', '冰豆花', '蛋', '豆皮', '方便面', '粉丝', '鱼丸', '培根', '鹌鹑蛋', '午餐肉', '宽粉', '鱼豆腐', '酸梅汤', '牛奶鸡蛋醪糟'] },
    { id: 'set', name: '套餐', keywords: ['套餐', '冒菜'] },
  ],
  rice: [
    { id: 'cover_rice', name: '盖饭', keywords: ['饭', '套餐', '黄焖', '卤肉饭', '铁板', '泡椒', '干煸', '酸辣土豆'] },
    { id: 'soup_sides', name: '汤品/小吃', keywords: ['汤', '蒸蛋', '蒸南瓜', '蒸芋头', '油条', '豆浆', '蛋饼', '小笼包', '煎饺', '米饭', '卤蛋', '卤豆腐', '卤豆干', '酸菜', '例汤'] },
    { id: 'other', name: '其他', keywords: [] },
  ],
  tea: [
    { id: 'pure_tea', name: '纯茶', keywords: ['纯茶', '铁观音', '茉莉雪芽', '绿妍', '四季春'] },
    { id: 'coffee', name: '咖啡', keywords: ['美式', '拿铁', '澳瑞白', '玛奇朵', '摩卡', '生椰', '椰云', '冰吸'] },
    { id: 'fruit_tea', name: '鲜果茶', keywords: ['葡萄', '莓', '桃李', '椰椰', '柠檬', '橙', '西瓜', '芒果', '百香果', '蜜桃', '草莓', '杨枝甘露', '棒打', '鲜橙', '西米露', '冰酿', '乌龙'] },
    { id: 'milk_tea', name: '奶茶', keywords: ['奶茶', '波波', '珍珠', '芋圆', '烧仙草', '芋泥', '血糯米', '燕麦奶', '红豆奶', '乳茶', '双重奏', '玉麒麟', '啵啵'] },
    { id: 'snacks', name: '冰淇淋/小食', keywords: ['冰淇淋', '圣代', '甜筒'] },
  ],
  dessert: [
    { id: 'classic', name: '经典甜品', keywords: ['杨枝甘露', '双皮奶', '姜汁撞奶', '龟苓膏', '白雪', '班戟', '捞', '糯米糍', '芭菲', '撞奶', '小丸子', '椰汁', '脏脏', '芋仙', '多芒'] },
    { id: 'cake', name: '蛋糕/西点', keywords: ['蛋糕', '千层', '提拉米苏', '芝士', '慕斯', '泡芙', '蛋挞', '巧克力冰山', '毛巾卷', '盒子', '雪媚娘', '酥', '曲奇', '牛轧糖', '蝴蝶酥', '菠萝油', '布甸', '半熟', '小贝', '凤梨酥', '绿豆糕', '雪花酥', '蛋黄酥', '吐司', '面包', '蛋糕卷', '肉松'] },
    { id: 'ice', name: '冰品', keywords: ['冰淇淋', '暴风雪', '冰沙', '甜筒', '圣代', '奶昔', '仙草', '芋圆', '牛奶冰', '芋头牛奶'] },
    { id: 'drinks', name: '饮品', keywords: ['咖啡', '拿铁', '奶茶', '珍珠', '抹茶拿铁'] },
  ],
  night: [
    { id: 'hotpot_base', name: '锅底', keywords: ['锅底', '红汤'] },
    { id: 'skewer', name: '串串', keywords: ['串'] },
    { id: 'meat', name: '荤菜', keywords: ['牛肉', '毛肚', '虾滑', '黄喉', '鸭肠', '肥牛', '羊肉', '鸭血', '小郡肝', '午餐肉', '猪蹄', '鸡爪', '酥肉', '郡肝', '鸭脖', '鸭锁骨', '鸭翅', '鸭掌', '鸭头', '鸭舌', '夫妻肺片', '藤椒鸡', '百味鸡', '手切', '卤牛', '捞派'] },
    { id: 'veg', name: '素菜', keywords: ['豆腐', '宽粉', '藕片', '毛豆', '花生', '豆干', '金针菇', '冻豆腐', '土豆', '豆皮', '鹌鹑蛋'] },
    { id: 'snacks_drinks', name: '小吃/饮品', keywords: ['冰粉', '糍粑', '酸梅汤', '手工面', '番茄牛肉饭', '麻酱', '冒菜', '冒粉', '冒面', '卤', '蘸料'] },
  ],
};

function resolveSubCategories(categoryId: string, items: RawItem[]): { subCategories: MenuSubCategory[]; itemSubIds: (string | undefined)[] } {
  const templates = SUB_CATEGORY_MAP[categoryId];
  if (!templates) return { subCategories: [], itemSubIds: items.map(() => undefined) };
  const itemSubIds = items.map((item) => {
    for (const t of templates) {
      if (t.keywords.some((kw) => item.name.includes(kw))) return t.id;
    }
    return templates[0].id;
  });
  const used = new Set(itemSubIds);
  const subCategories = templates.filter((t) => used.has(t.id)).map(({ id, name }) => ({ id, name }));
  return { subCategories, itemSubIds };
}

let _sid = 0;
function buildStore(raw: RawStore): StoreDetail {
  const id = `store-${String(++_sid).padStart(2, '0')}`;
  const { subCategories, itemSubIds } = resolveSubCategories(raw.categoryId, raw.items);
  const menu: MenuItem[] = raw.items.map((item, idx) => {
    const itemId = `${id}-item-${String(idx + 1).padStart(2, '0')}`;
    const defaultSpecs: SpecGroup[] = [sizeSpec(itemId)];
    const specs = item.specs
      ? item.specs.map((s, si) => ({ ...defaultSpecs[si] ?? sizeSpec(itemId), ...s, id: s.id ?? `${itemId}-spec-${si}`, options: (s.options ?? defaultSpecs[si]?.options ?? []).map((o, oi) => ({ ...o, id: o.id ?? `${itemId}-opt-${si}-${oi}` })) }))
      : defaultSpecs;
    const calorieEstimate = estimateCalories(item.name, raw.categoryId);
    return {
      id: itemId,
      storeId: id,
      categoryId: raw.categoryId,
      subCategoryId: subCategories.length ? itemSubIds[idx] : undefined,
      name: item.name,
      subtitle: item.subtitle,
      basePriceCents: yuan(item.price),
      ...calorieEstimate,
      monthlySales: Math.floor(30 + Math.random() * 800),
      sourceType: 'original',
      specGroups: withCalorieDeltas(specs, calorieEstimate.caloriesKcal),
    };
  });
  return {
    id,
    name: transformStoreName(raw.name),
    categoryId: raw.categoryId,
    description: raw.description,
    tags: raw.tags,
    deliveryFeeCents: yuan(raw.deliveryFee),
    packingFeeCents: yuan(raw.packingFee),
    minimumOrderCents: yuan(raw.minOrder),
    virtualDeliveryMinutes: raw.deliveryMin,
    monthlySales: raw.monthlySales,
    distanceKm: raw.distanceKm,
    rating: raw.rating,
    recentViewers: Math.floor(50 + Math.random() * 1200),
    systemHeat: Math.floor(60 + Math.random() * 40),
    sourceType: 'original',
    menu,
    subCategories: subCategories.length ? subCategories : undefined,
  };
}

/* ═══════════════════════════════════════════════
   Seed Data — 8 categories × 10+ stores
   ═══════════════════════════════════════════════ */

const rawStores: RawStore[] = [

  // ─────── 烧烤 (bbq) ───────
  { name: '炭火小院', categoryId: 'bbq', description: '专注烧烤20年，原味鲜烤不腌制', tags: ['老字号', '堂食'], deliveryFee: 3, packingFee: 1, minOrder: 30, deliveryMin: 35, monthlySales: 1856, distanceKm: 1.2, rating: 4.7, items: [
    { name: '烤羊肉串(10串)', subtitle: '新疆羔羊，现串现烤', price: 58, specs: [spiceSpec('') as any] },
    { name: '烤牛肉串(10串)', price: 62 },
    { name: '烤鸡翅中(6只)', subtitle: '蜜汁腌料', price: 36 },
    { name: '烤猪蹄(半只)', subtitle: '先卤后烤，外焦里糯', price: 32 },
    { name: '烤生蚝(6只)', subtitle: '蒜蓉粉丝', price: 48 },
    { name: '烤韭菜', price: 16 },
    { name: '烤茄子(整条)', subtitle: '蒜蓉烤茄', price: 22 },
    { name: '锡纸金针菇', price: 18 },
    { name: '烤馒头片(2片)', price: 8 },
    { name: '锡纸花蛤', subtitle: '蒜香鲜辣', price: 32 },
    { name: '烤全翅(2只)', price: 28 },
    { name: '冰镇毛豆', price: 12 },
  ]},
  { name: '烤串物语', categoryId: 'bbq', description: '延吉风味烤串，自动翻转', tags: ['朝鲜族风味', '自动烤炉'], deliveryFee: 4, packingFee: 1, minOrder: 40, deliveryMin: 40, monthlySales: 1243, distanceKm: 2.1, rating: 4.6, items: [
    { name: '丰茂烤牛肉(10串)', subtitle: '延边黄牛', price: 68 },
    { name: '烤牛板筋(10串)', price: 45 },
    { name: '烤羊排串(5串)', price: 55 },
    { name: '烤猪五花(10串)', price: 42 },
    { name: '辣炒花蛤', price: 35 },
    { name: '拌冷面', subtitle: '延吉特色', price: 22 },
    { name: '石锅拌饭', price: 28 },
    { name: '烤明太鱼', price: 38 },
    { name: '大拉皮', price: 18 },
    { name: '烤辣椒', price: 12 },
    { name: '打糕', price: 16 },
  ]},
  { name: '古法羊肉串', categoryId: 'bbq', description: '呼伦贝尔6月龄羔羊，只用好羊肉', tags: ['品牌连锁', '夜宵热门'], deliveryFee: 5, packingFee: 2, minOrder: 50, deliveryMin: 38, monthlySales: 2104, distanceKm: 1.8, rating: 4.5, items: [
    { name: '羊肉串(10串)', subtitle: '呼伦贝尔羔羊', price: 65 },
    { name: '羊腰子(5串)', price: 45 },
    { name: '烤羊排', subtitle: '半斤起', price: 78 },
    { name: '脆骨(10串)', price: 38 },
    { name: '烤面包片(3片)', price: 12 },
    { name: '锡纸娃娃菜', price: 18 },
    { name: '烤鸡心(10串)', price: 30 },
    { name: '烤大蒜(10串)', price: 15 },
    { name: '毛豆花生拼盘', price: 22 },
    { name: '疙瘩汤', price: 18 },
    { name: '凉菜拼盘', price: 28 },
  ]},
  { name: '烤鱼小匠', categoryId: 'bbq', description: '川味烤鱼代表，麻辣鲜香', tags: ['网红店', '排队王'], deliveryFee: 5, packingFee: 2, minOrder: 60, deliveryMin: 45, monthlySales: 1678, distanceKm: 2.5, rating: 4.6, items: [
    { name: '经典麻辣烤鱼', subtitle: '2.5斤起', price: 128 },
    { name: '蒜香烤鱼', price: 118 },
    { name: '酸菜烤鱼', price: 118 },
    { name: '豆豉烤鱼', price: 108 },
    { name: '锡纸茄子', price: 22 },
    { name: '卤鸡爪(6只)', price: 28 },
    { name: '冒菜', price: 32 },
    { name: '炸酥肉', price: 25 },
    { name: '冰粉', price: 12 },
    { name: '凉拌黄瓜', price: 15 },
  ]},
  { name: '串吧小馆', categoryId: 'bbq', description: '东北烧烤，量大实惠', tags: ['东北风味', '量大'], deliveryFee: 3, packingFee: 1, minOrder: 25, deliveryMin: 30, monthlySales: 987, distanceKm: 1.5, rating: 4.3, items: [
    { name: '羊肉串(10串)', price: 45 },
    { name: '牛胸口(10串)', subtitle: '东北特色', price: 55 },
    { name: '烤油豆皮(5串)', price: 20 },
    { name: '烤蚕蛹(10串)', price: 35 },
    { name: '大腰子(5串)', price: 40 },
    { name: '东北烤冷面', price: 15 },
    { name: '拍黄瓜', price: 12 },
    { name: '花生毛豆', price: 15 },
    { name: '蒜蓉烤扇贝(6只)', price: 48 },
    { name: '烤玉米', price: 10 },
  ]},
  { name: '串亭居酒屋', categoryId: 'bbq', description: '日式烧烤 × 居酒屋氛围', tags: ['日式', '居酒屋'], deliveryFee: 5, packingFee: 2, minOrder: 50, deliveryMin: 35, monthlySales: 856, distanceKm: 3.0, rating: 4.4, items: [
    { name: '和牛烤牛肉(8片)', price: 88 },
    { name: '厚切牛舌(5片)', price: 68 },
    { name: '烤五花肉(10串)', price: 42 },
    { name: '烤鸡皮(5串)', price: 25 },
    { name: '烤银杏(10颗)', price: 18 },
    { name: '烤年糕(5串)', price: 20 },
    { name: '盐烤秋刀鱼', price: 32 },
    { name: '枝豆(盐味)', price: 15 },
    { name: '味噌汤', price: 18 },
    { name: '烤饭团(2个)', price: 22 },
  ]},
  { name: '翅吧小馆', categoryId: 'bbq', description: '烤鸡翅专家，18种口味', tags: ['鸡翅专家', '老牌'], deliveryFee: 4, packingFee: 1, minOrder: 30, deliveryMin: 32, monthlySales: 1432, distanceKm: 1.6, rating: 4.5, items: [
    { name: '秘制烤翅(6只)', subtitle: '招牌18味', price: 42 },
    { name: '变态辣翅(6只)', price: 42 },
    { name: '蜜汁烤翅(6只)', price: 42 },
    { name: '烤鸡翅根(6只)', price: 32 },
    { name: '烤鸡腿(2只)', price: 28 },
    { name: '烤馒头片', price: 8 },
    { name: '锡纸金针菇', price: 18 },
    { name: '烤玉米', price: 10 },
    { name: '凉拌木耳', price: 16 },
    { name: '疙瘩汤', price: 18 },
  ]},
  { name: '小腰专门店', categoryId: 'bbq', description: '以小腰闻名的烧烤店', tags: ['网红', '夜宵'], deliveryFee: 5, packingFee: 2, minOrder: 40, deliveryMin: 35, monthlySales: 1125, distanceKm: 2.3, rating: 4.4, items: [
    { name: '招牌小腰(10串)', subtitle: '镇店之宝', price: 50 },
    { name: '羊肉串(10串)', price: 55 },
    { name: '烤鸡脆骨(10串)', price: 35 },
    { name: '烤心管(10串)', price: 38 },
    { name: '烤实蛋(5串)', price: 20 },
    { name: '烤韭菜', price: 15 },
    { name: '锡纸娃娃菜', price: 18 },
    { name: '花毛一体', price: 18 },
    { name: '凉拌皮蛋', price: 16 },
    { name: '炒方便面', price: 18 },
  ]},
  { name: '串聚吧', categoryId: 'bbq', description: '深夜烧烤聚集地', tags: ['深夜营业', '啤酒'], deliveryFee: 3, packingFee: 1, minOrder: 25, deliveryMin: 28, monthlySales: 762, distanceKm: 0.8, rating: 4.2, items: [
    { name: '羊肉串(10串)', price: 48 },
    { name: '板筋(10串)', price: 40 },
    { name: '烤鸡翅(6只)', price: 36 },
    { name: '烤馒头', price: 8 },
    { name: '烤大虾(5只)', price: 55 },
    { name: '锡纸豆腐', price: 18 },
    { name: '蒜蓉扇贝(6只)', price: 45 },
    { name: '拍黄瓜', price: 12 },
    { name: '花生米', price: 10 },
    { name: '酸辣汤', price: 18 },
  ]},
  { name: '汉斯烤肉屋', categoryId: 'bbq', description: '巴西烤肉自助风格，按份售卖', tags: ['巴西烤肉', '自助风格'], deliveryFee: 4, packingFee: 2, minOrder: 40, deliveryMin: 40, monthlySales: 634, distanceKm: 3.5, rating: 4.1, items: [
    { name: '烤牛肩肉(200g)', subtitle: '巴西风味', price: 58 },
    { name: '烤羊腿肉(200g)', price: 62 },
    { name: '烤猪颈肉(200g)', price: 45 },
    { name: '烤鸡翅(6只)', price: 35 },
    { name: '烤牛舌(150g)', price: 55 },
    { name: '烤菠萝', price: 15 },
    { name: '沙拉吧', price: 25 },
    { name: '玉米浓汤', price: 18 },
    { name: '烤香蕉', price: 15 },
    { name: '烤肠拼盘', price: 32 },
  ]},

  // ─────── 炸鸡 (fried) ───────
  { name: '鸡排小铺', categoryId: 'fried', description: '外酥里嫩的鸡排王者', tags: ['国民小吃', '随处可见'], deliveryFee: 2, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 3210, distanceKm: 0.5, rating: 4.1, items: [
    { name: '招牌大鸡排', subtitle: '比脸还大', price: 12 },
    { name: '霸王鸡排', subtitle: '加量50%', price: 16 },
    { name: '轰炸大鱿鱼', price: 18 },
    { name: '脆皮鸡翅(3只)', price: 15 },
    { name: '鸡米花(大)', price: 12 },
    { name: '甘梅地瓜条', price: 10 },
    { name: '盐酥鸡', price: 15 },
    { name: '脆皮炸鲜奶', price: 12 },
    { name: '香辣鸡腿', price: 12 },
    { name: '鸡肉串(3串)', price: 10 },
  ]},
  { name: '喜饱饱', categoryId: 'fried', description: '平价西式快餐，量大管饱', tags: ['平价', '全国连锁'], deliveryFee: 3, packingFee: 1, minOrder: 20, deliveryMin: 25, monthlySales: 4521, distanceKm: 0.8, rating: 4.0, items: [
    { name: '香辣鸡腿堡', price: 12 },
    { name: '蜜汁手扒鸡(半只)', subtitle: '整只烤制', price: 29 },
    { name: '脆皮炸鸡翅(4只)', price: 18 },
    { name: '上校鸡块(8块)', price: 12 },
    { name: '香辣鸡腿(2只)', price: 12 },
    { name: '薯条(大)', price: 10 },
    { name: '墨西哥鸡肉卷', price: 15 },
    { name: '老北京鸡肉卷', price: 15 },
    { name: '鸡米花', price: 10 },
    { name: '可乐鸡翅(5只)', price: 22 },
  ]},
  { name: '整只炸鸡铺', categoryId: 'fried', description: '整只炸鸡专家', tags: ['整只炸鸡', '分享装'], deliveryFee: 4, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 1876, distanceKm: 1.5, rating: 4.3, items: [
    { name: '整只炸鸡', subtitle: '招牌原味', price: 58 },
    { name: '半只炸鸡', price: 35 },
    { name: '蒜香炸鸡(半只)', price: 38 },
    { name: '香辣炸鸡(半只)', price: 38 },
    { name: '炸鸡年糕', price: 18 },
    { name: '炸鸡翅(6只)', price: 28 },
    { name: '薯条(大份)', price: 12 },
    { name: '洋葱圈', price: 15 },
    { name: '炸鸡腿(2只)', price: 22 },
    { name: '芝士球(6个)', price: 18 },
  ]},
  { name: '台式鸡车', categoryId: 'fried', description: '台式炸鸡排，古早味传承', tags: ['台湾风味', '鸡排'], deliveryFee: 3, packingFee: 1, minOrder: 20, deliveryMin: 22, monthlySales: 2340, distanceKm: 1.0, rating: 4.4, items: [
    { name: '超级鸡排', subtitle: '现炸大鸡排', price: 16 },
    { name: '椒麻鸡排', price: 18 },
    { name: '脆皮鸡翅(4只)', price: 22 },
    { name: '甘梅薯条', price: 12 },
    { name: '盐酥鸡', price: 18 },
    { name: '花枝丸(6颗)', price: 15 },
    { name: '鸡米花', price: 12 },
    { name: '脆皮鸡腿', price: 18 },
    { name: '甜不辣', price: 12 },
    { name: '米血糕', price: 10 },
  ]},
  { name: '韩式炸鸡屋', categoryId: 'fried', description: '正宗韩式炸鸡，酥脆多汁', tags: ['韩式', '甜辣'], deliveryFee: 5, packingFee: 2, minOrder: 45, deliveryMin: 35, monthlySales: 1567, distanceKm: 2.0, rating: 4.6, items: [
    { name: '原味炸鸡(半份)', subtitle: '双重炸制更酥脆', price: 55 },
    { name: '甜辣炸鸡(半份)', price: 58 },
    { name: '酱油蒜香炸鸡(半份)', price: 58 },
    { name: '芝士炸鸡(半份)', price: 62 },
    { name: '雪花炸鸡(半份)', subtitle: '蒜香粉', price: 58 },
    { name: '炸鸡年糕', price: 25 },
    { name: '薯条', price: 15 },
    { name: '腌萝卜', price: 8 },
    { name: '可乐鸡翅(5只)', price: 32 },
    { name: '辣炒年糕', price: 28 },
  ]},
  { name: '爆浆鸡排铺', categoryId: 'fried', description: '爆浆鸡排开创者', tags: ['爆浆', '人气'], deliveryFee: 2, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 2890, distanceKm: 0.6, rating: 4.2, items: [
    { name: '爆浆鸡排', subtitle: '芝士流心', price: 18 },
    { name: '招牌大鸡排', price: 14 },
    { name: '甘梅鸡排', price: 16 },
    { name: '椒盐鸡排', price: 14 },
    { name: '鸡米花', price: 10 },
    { name: '鸡翅包饭', price: 16 },
    { name: '地瓜条', price: 10 },
    { name: '轰炸鱿鱼', price: 15 },
    { name: '脆皮鸡翅(3只)', price: 15 },
    { name: '烤肠', price: 6 },
  ]},
  { name: '咔滋炸鸡', categoryId: 'fried', description: '脆皮炸鸡专家，咔滋脆皮', tags: ['品牌连锁', '脆皮'], deliveryFee: 4, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 2156, distanceKm: 1.2, rating: 4.3, items: [
    { name: '脆皮炸鸡(3块)', subtitle: '咔滋脆皮', price: 32 },
    { name: '脆皮手枪腿', price: 22 },
    { name: '辣味脆皮炸鸡(3块)', price: 32 },
    { name: '脆皮炸鸡翅(4只)', price: 22 },
    { name: '孜然鸡柳', price: 15 },
    { name: '上校鸡块', price: 12 },
    { name: '咖喱饭', price: 25 },
    { name: '薯条(大)', price: 12 },
    { name: '脆皮鸡腿', price: 18 },
    { name: '鸡排大亨', price: 18 },
  ]},
  { name: '圆盘鸡排', categoryId: 'fried', description: '大脸盘鸡排，实惠管饱', tags: ['超大', '实惠'], deliveryFee: 2, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 1678, distanceKm: 0.9, rating: 4.1, items: [
    { name: '圆盘鸡排', subtitle: '直径30cm', price: 15 },
    { name: '椒麻大鸡排', price: 17 },
    { name: '甘梅大鸡排', price: 17 },
    { name: '盐酥鸡', price: 15 },
    { name: '鸡米花', price: 10 },
    { name: '脆皮鸡翅(3只)', price: 15 },
    { name: '地瓜条', price: 10 },
    { name: '轰炸鱿鱼', price: 15 },
    { name: '花枝丸', price: 12 },
    { name: '烤肠(2根)', price: 8 },
  ]},
  { name: '美式炸鸡屋', categoryId: 'fried', description: '美国路易斯安那风味炸鸡', tags: ['美式', '路易斯安那'], deliveryFee: 5, packingFee: 2, minOrder: 40, deliveryMin: 30, monthlySales: 1345, distanceKm: 2.8, rating: 4.5, items: [
    { name: '经典脆皮炸鸡(3块)', price: 45 },
    { name: '辣味脆皮炸鸡(3块)', price: 45 },
    { name: '脆皮鸡柳(5条)', price: 32 },
    { name: '炸鸡翅(4只)', price: 28 },
    { name: '比司吉面包(2个)', price: 18 },
    { name: '卡真薯条', price: 15 },
    { name: '红豆派', price: 12 },
    { name: '鸡块(8块)', price: 25 },
    { name: '洋葱圈', price: 15 },
    { name: '鸡肉三明治', price: 35 },
  ]},
  { name: '韩式蜜炸鸡', categoryId: 'fried', description: '正宗韩国炸鸡品牌', tags: ['韩国进口', '正宗'], deliveryFee: 5, packingFee: 2, minOrder: 50, deliveryMin: 35, monthlySales: 987, distanceKm: 3.2, rating: 4.5, items: [
    { name: '原味炸鸡(整份)', price: 89 },
    { name: '甜辣炸鸡(整份)', price: 92 },
    { name: '蒜香酱油炸鸡(整份)', price: 92 },
    { name: '芝士炸鸡(整份)', price: 95 },
    { name: '辣炒年糕', price: 32 },
    { name: '炸鸡披萨', price: 55 },
    { name: '韩式薯条', price: 18 },
    { name: '腌萝卜块', price: 10 },
    { name: '鱼饼串(3串)', price: 22 },
    { name: '紫菜包饭', price: 28 },
  ]},

  // ─────── 汉堡 (burger) ───────
  { name: '炸鸡小馆', categoryId: 'burger', description: '香脆炸鸡，快乐全家餐', tags: ['香脆炸鸡', '人气'], deliveryFee: 6, packingFee: 2, minOrder: 30, deliveryMin: 30, monthlySales: 8920, distanceKm: 0.8, rating: 4.4, items: [
    { name: '香辣鸡腿堡', subtitle: '经典人气', price: 19 },
    { name: '新奥尔良烤鸡腿堡', price: 19 },
    { name: '劲脆鸡腿堡', price: 19 },
    { name: '吮指原味鸡(2块)', price: 24 },
    { name: '热辣香骨鸡(5块)', price: 28 },
    { name: '香辣鸡翅(4只)', price: 16 },
    { name: '上校鸡块(5块)', price: 14 },
    { name: '薯条(大)', price: 14 },
    { name: '葡式蛋挞(2只)', price: 16 },
    { name: '老北京鸡肉卷', price: 17 },
    { name: '土豆泥', price: 12 },
    { name: '甜筒冰淇淋', price: 8 },
  ]},
  { name: '麦香堡', categoryId: 'burger', description: '现做汉堡，快乐每一口', tags: ['招牌汉堡', '现做现卖'], deliveryFee: 6, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 9215, distanceKm: 0.6, rating: 4.5, items: [
    { name: '巨无霸', subtitle: '双层牛肉饼', price: 26 },
    { name: '麦辣鸡腿堡', price: 20 },
    { name: '板烧鸡腿堡', subtitle: '去骨鸡腿', price: 22 },
    { name: '麦香鱼', price: 20 },
    { name: '麦乐鸡(10块)', price: 22 },
    { name: '薯条(大)', price: 14 },
    { name: '麦旋风', price: 14 },
    { name: '圆筒冰淇淋', price: 6 },
    { name: '香芋派', price: 10 },
    { name: '鸡翅(2对)', price: 16 },
    { name: '吉士汉堡', price: 14 },
    { name: '双层吉士汉堡', price: 22 },
  ]},
  { name: '火烤堡', categoryId: 'burger', description: '真正火烤，不是油炸', tags: ['火烤牛肉', '现烤现卖'], deliveryFee: 6, packingFee: 2, minOrder: 35, deliveryMin: 32, monthlySales: 5432, distanceKm: 1.5, rating: 4.4, items: [
    { name: '皇堡', subtitle: '火烤牛肉饼', price: 32 },
    { name: '双层皇堡', price: 42 },
    { name: '天椒皇堡', price: 32 },
    { name: '脆皮鸡腿堡', price: 22 },
    { name: '鳕鱼堡', price: 22 },
    { name: '霸王鸡条(5条)', price: 18 },
    { name: '薯条(大)', price: 14 },
    { name: '洋葱圈(8个)', price: 16 },
    { name: '嫩牛五方', price: 18 },
    { name: '圣代', price: 12 },
    { name: '芝士牛肉堡', price: 28 },
  ]},
  { name: '纽约汉堡屋', categoryId: 'burger', description: '纽约风味手作汉堡', tags: ['高端', '纽约风味'], deliveryFee: 8, packingFee: 3, minOrder: 60, deliveryMin: 40, monthlySales: 2345, distanceKm: 3.0, rating: 4.7, items: [
    { name: 'ShackBurger', subtitle: '安格斯牛肉', price: 58 },
    { name: 'SmokeShack', subtitle: '烟熏辣椒+培根', price: 68 },
    { name: 'Shack Stack(素食)', price: 52 },
    { name: '热狗', price: 38 },
    { name: '芝士薯条', price: 32 },
    { name: '波浪薯条', price: 25 },
    { name: '奶昔(香草)', price: 38 },
    { name: '奶昔(巧克力)', price: 38 },
    { name: '鸡柳堡', price: 48 },
    { name: '蘑菇牛肉堡', price: 62 },
  ]},
  { name: '国潮汉堡', categoryId: 'burger', description: '手擀现烤堡胚，中国味汉堡', tags: ['国潮', '现烤堡胚'], deliveryFee: 4, packingFee: 2, minOrder: 25, deliveryMin: 28, monthlySales: 6780, distanceKm: 1.0, rating: 4.5, items: [
    { name: '香辣鸡腿堡', subtitle: '手擀堡胚', price: 15 },
    { name: '板烧凤梨堡', price: 18 },
    { name: '麻婆豆腐堡', subtitle: '中国味', price: 18 },
    { name: '北京烤鸭堡', price: 22 },
    { name: '鱼香肉丝堡', price: 18 },
    { name: '藤椒鸡腿堡', price: 16 },
    { name: '粗薯', price: 12 },
    { name: '鸡翅(2对)', price: 15 },
    { name: '鸡块(6块)', price: 12 },
    { name: '冰淇淋', price: 6 },
  ]},
  { name: '快乐汉堡', categoryId: 'burger', description: '平价汉堡专家', tags: ['平价', '校园周边'], deliveryFee: 3, packingFee: 1, minOrder: 15, deliveryMin: 22, monthlySales: 3456, distanceKm: 0.5, rating: 4.0, items: [
    { name: '香辣鸡腿堡', price: 10 },
    { name: '双层牛肉堡', price: 18 },
    { name: '板烧鸡腿堡', price: 12 },
    { name: '鳕鱼堡', price: 12 },
    { name: '嫩牛五方', price: 12 },
    { name: '薯条(大)', price: 8 },
    { name: '鸡翅(2对)', price: 10 },
    { name: '鸡米花', price: 8 },
    { name: '上校鸡块', price: 8 },
    { name: '甜筒', price: 4 },
  ]},
  { name: '牛堡小馆', categoryId: 'burger', description: '专注牛肉汉堡，手作厚实', tags: ['手作牛肉', '厚实'], deliveryFee: 5, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 1567, distanceKm: 2.0, rating: 4.3, items: [
    { name: '经典牛肉堡', subtitle: '150g牛肉饼', price: 32 },
    { name: '双层芝士牛肉堡', price: 42 },
    { name: '培根牛肉堡', price: 35 },
    { name: '蘑菇牛肉堡', price: 35 },
    { name: '香辣鸡腿堡', price: 20 },
    { name: '薯条(大)', price: 14 },
    { name: '洋葱圈', price: 16 },
    { name: '芝士鸡柳堡', price: 22 },
    { name: '牛肉卷', price: 25 },
    { name: '圣代', price: 12 },
  ]},
  { name: '小堡当家', categoryId: 'burger', description: '社区汉堡小店，新鲜现做', tags: ['社区店', '新鲜'], deliveryFee: 3, packingFee: 1, minOrder: 20, deliveryMin: 25, monthlySales: 876, distanceKm: 0.8, rating: 4.2, items: [
    { name: '经典鸡腿堡', price: 14 },
    { name: '香辣鸡腿堡', price: 14 },
    { name: '牛肉芝士堡', price: 25 },
    { name: '鳕鱼堡', price: 16 },
    { name: '鸡肉卷', price: 15 },
    { name: '薯条', price: 10 },
    { name: '鸡米花', price: 10 },
    { name: '鸡翅(2对)', price: 12 },
    { name: '鸡块', price: 10 },
    { name: '冰淇淋', price: 5 },
  ]},
  { name: '加州汉堡屋', categoryId: 'burger', description: '美国加州汉堡品牌', tags: ['美式', '加州风味'], deliveryFee: 6, packingFee: 2, minOrder: 40, deliveryMin: 32, monthlySales: 1234, distanceKm: 2.5, rating: 4.4, items: [
    { name: '招牌汉堡', subtitle: '火焰烤牛肉', price: 38 },
    { name: '双层芝士堡', price: 48 },
    { name: '蘑菇瑞士芝士堡', price: 45 },
    { name: '辣味鸡柳堡', price: 28 },
    { name: '炸鸡翅(4只)', price: 25 },
    { name: '薯条(大)', price: 16 },
    { name: '洋葱圈', price: 18 },
    { name: '奶昔(香草)', price: 22 },
    { name: '奶昔(巧克力)', price: 22 },
    { name: '牛肉热狗', price: 25 },
  ]},
  { name: '世纪汉堡屋', categoryId: 'burger', description: '本土精品汉堡品牌', tags: ['本土品牌', '精品'], deliveryFee: 4, packingFee: 2, minOrder: 25, deliveryMin: 28, monthlySales: 1098, distanceKm: 1.8, rating: 4.2, items: [
    { name: '招牌牛肉堡', price: 28 },
    { name: '黑椒牛肉堡', price: 30 },
    { name: '香辣鸡腿堡', price: 16 },
    { name: '蜜汁鸡腿堡', price: 16 },
    { name: '鳕鱼堡', price: 18 },
    { name: '薯条', price: 12 },
    { name: '鸡米花', price: 10 },
    { name: '鸡翅(2对)', price: 14 },
    { name: '鸡块(6块)', price: 12 },
    { name: '甜筒', price: 5 },
  ]},

  // ─────── 粉面 (noodles) ───────
  { name: '书房捞面', categoryId: 'noodles', description: '书房里的养生面，草本汤底', tags: ['养生面', '书房环境'], deliveryFee: 5, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 3456, distanceKm: 1.5, rating: 4.6, items: [
    { name: '草本汤面', subtitle: '招牌养生', price: 38 },
    { name: '酸菜五花肉面', price: 35 },
    { name: '番茄鸡蛋面', price: 28 },
    { name: '红烧牛肉面', subtitle: '大块牛腱', price: 42 },
    { name: '葱油拌面', price: 22 },
    { name: '酸汤肥牛面', price: 38 },
    { name: '草本肥牛面', price: 42 },
    { name: '老卤猪蹄面', price: 45 },
    { name: '溏心蛋(加料)', price: 6 },
    { name: '卤豆腐(加料)', price: 5 },
  ]},
  { name: '巴蜀小面', categoryId: 'noodles', description: '重庆小面，地道巴蜀味', tags: ['重庆小面', '地道'], deliveryFee: 4, packingFee: 1, minOrder: 20, deliveryMin: 25, monthlySales: 2890, distanceKm: 1.0, rating: 4.5, items: [
    { name: '重庆小面', subtitle: '麻辣鲜香', price: 18 },
    { name: '豌杂面', subtitle: '豌豆+杂酱', price: 22 },
    { name: '酸菜肉丝面', price: 20 },
    { name: '番茄鸡蛋面', price: 18 },
    { name: '肥肠面', price: 25 },
    { name: '牛肉面', price: 28 },
    { name: '红油抄手', price: 18 },
    { name: '山城小汤圆', price: 12 },
    { name: '冰粉', price: 10 },
    { name: '煎蛋(加料)', price: 3 },
  ]},
  { name: '常德米粉馆', categoryId: 'noodles', description: '正宗常德牛肉米粉', tags: ['湖南米粉', '常德味'], deliveryFee: 5, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 2345, distanceKm: 1.8, rating: 4.5, items: [
    { name: '红烧牛肉粉', subtitle: '常德原味', price: 28 },
    { name: '麻辣牛肉粉', price: 28 },
    { name: '酸菜肉丝粉', price: 22 },
    { name: '肉蛋双飞粉', subtitle: '牛肉+卤蛋', price: 32 },
    { name: '排骨粉', price: 30 },
    { name: '肥肠粉', price: 25 },
    { name: '葱油拌粉', price: 18 },
    { name: '臭豆腐', price: 15 },
    { name: '糖油粑粑', price: 10 },
    { name: '冰豆花', price: 12 },
  ]},
  { name: '金城牛肉面', categoryId: 'noodles', description: '一清二白三红四绿五黄', tags: ['兰州牛肉面', '手工拉面'], deliveryFee: 4, packingFee: 1, minOrder: 20, deliveryMin: 25, monthlySales: 2678, distanceKm: 1.2, rating: 4.4, items: [
    { name: '经典牛肉面', subtitle: '手工拉面', price: 22 },
    { name: '大肉面', price: 28 },
    { name: '牛肉拌面', price: 25 },
    { name: '酸菜牛肉面', price: 25 },
    { name: '加肉版牛肉面', subtitle: '双倍牛肉', price: 35 },
    { name: '牛肉凉面', price: 22 },
    { name: '酿皮子', price: 15 },
    { name: '甜醅子', price: 10 },
    { name: '灰豆汤', price: 10 },
    { name: '卤蛋(加料)', price: 4 },
  ]},
  { name: '清汤拉面馆', categoryId: 'noodles', description: '手工现拉，汤清面筋', tags: ['手工拉面', '清真'], deliveryFee: 5, packingFee: 2, minOrder: 25, deliveryMin: 28, monthlySales: 3120, distanceKm: 1.5, rating: 4.5, items: [
    { name: '牛肉面(细面)', price: 25 },
    { name: '牛肉面(宽面)', price: 25 },
    { name: '牛肉面(韭叶)', price: 25 },
    { name: '加肉牛肉面', price: 38 },
    { name: '牛肉拌面', price: 28 },
    { name: '干拌牛肉面', price: 30 },
    { name: '酿皮', price: 16 },
    { name: '灰豆子', price: 12 },
    { name: '牛奶鸡蛋醪糟', price: 15 },
    { name: '羊肉串(5串)', price: 25 },
  ]},
  { name: '自选麻辣烫', categoryId: 'noodles', description: '自选食材，称重计价', tags: ['麻辣烫', '自选'], deliveryFee: 3, packingFee: 2, minOrder: 20, deliveryMin: 25, monthlySales: 4567, distanceKm: 0.8, rating: 4.2, items: [
    { name: '麻辣烫(荤素搭配500g)', price: 28 },
    { name: '麻辣烫(纯素300g)', price: 15 },
    { name: '麻辣烫(纯荤300g)', price: 35 },
    { name: '冒菜套餐', subtitle: '固定搭配', price: 25 },
    { name: '酸辣粉', price: 16 },
    { name: '宽粉', price: 8 },
    { name: '方便面', price: 5 },
    { name: '豆皮', price: 5 },
    { name: '鱼豆腐', price: 5 },
    { name: '午餐肉', price: 8 },
  ]},
  { name: '骨汤麻辣烫', categoryId: 'noodles', description: '骨汤麻辣烫开创者', tags: ['骨汤', '全国连锁'], deliveryFee: 3, packingFee: 2, minOrder: 20, deliveryMin: 22, monthlySales: 5234, distanceKm: 0.6, rating: 4.3, items: [
    { name: '骨汤麻辣烫(500g)', price: 30 },
    { name: '番茄麻辣烫(500g)', price: 32 },
    { name: '酸辣麻辣烫(500g)', price: 30 },
    { name: '冒菜套餐', price: 28 },
    { name: '方便面(加料)', price: 5 },
    { name: '宽粉(加料)', price: 6 },
    { name: '粉丝(加料)', price: 5 },
    { name: '鱼丸(加料)', price: 5 },
    { name: '培根(加料)', price: 8 },
    { name: '鹌鹑蛋(加料)', price: 5 },
  ]},
  { name: '豚骨拉面屋', categoryId: 'noodles', description: '日式豚骨拉面', tags: ['日式', '豚骨汤底'], deliveryFee: 5, packingFee: 2, minOrder: 30, deliveryMin: 30, monthlySales: 1876, distanceKm: 2.0, rating: 4.2, items: [
    { name: '招牌豚骨拉面', price: 35 },
    { name: '豚骨拉面屋(大)', price: 42 },
    { name: '酸辣拉面', price: 32 },
    { name: '番茄牛腩拉面', price: 38 },
    { name: '日式煎饺(6个)', price: 22 },
    { name: '炸猪排', price: 28 },
    { name: '日式炒饭', price: 25 },
    { name: '唐扬鸡块', price: 22 },
    { name: '味噌拉面', price: 35 },
    { name: '溏心蛋(加料)', price: 6 },
  ]},
  { name: '瓦罐米线', categoryId: 'noodles', description: '瓦罐米线，鲜汤现煮', tags: ['米线', '瓦罐'], deliveryFee: 4, packingFee: 1, minOrder: 20, deliveryMin: 25, monthlySales: 2345, distanceKm: 1.0, rating: 4.3, items: [
    { name: '番茄肥牛米线', price: 28 },
    { name: '酸菜鱼米线', price: 32 },
    { name: '红烧牛肉米线', price: 28 },
    { name: '酸辣米线', price: 22 },
    { name: '麻辣米线', price: 22 },
    { name: '原味鸡汤米线', price: 25 },
    { name: '菌菇鸡汤米线', price: 28 },
    { name: '卤蛋(加料)', price: 4 },
    { name: '卤豆干(加料)', price: 5 },
    { name: '酸梅汤', price: 8 },
  ]},
  { name: '渔粉小馆', categoryId: 'noodles', description: '五谷杂粮渔粉，鲜而不腻', tags: ['渔粉', '五谷杂粮'], deliveryFee: 3, packingFee: 1, minOrder: 18, deliveryMin: 22, monthlySales: 1987, distanceKm: 0.8, rating: 4.3, items: [
    { name: '招牌渔粉', subtitle: '鲜鱼现熬汤底', price: 20 },
    { name: '酸辣渔粉', price: 20 },
    { name: '番茄渔粉', price: 22 },
    { name: '酸菜渔粉', price: 20 },
    { name: '麻辣渔粉', price: 20 },
    { name: '金汤渔粉', price: 25 },
    { name: '杂粮渔粉', subtitle: '五谷粉条', price: 22 },
    { name: '卤蛋(加料)', price: 3 },
    { name: '豆腐(加料)', price: 3 },
    { name: '酸梅汤', price: 6 },
  ]},

  // ─────── 盖饭 (rice) ───────
  { name: '乡味快餐', categoryId: 'rice', description: '中国中式快餐第一品牌', tags: ['中式快餐', '鸡汤'], deliveryFee: 4, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 6789, distanceKm: 1.0, rating: 4.6, items: [
    { name: '肥西老母鸡汤', subtitle: '招牌', price: 18 },
    { name: '梅菜扣肉饭', price: 22 },
    { name: '农家小炒肉饭', price: 22 },
    { name: '西红柿鸡蛋饭', price: 18 },
    { name: '鱼香肉丝饭', price: 20 },
    { name: '宫保鸡丁饭', price: 20 },
    { name: '红烧肉饭', price: 22 },
    { name: '酱香茄子饭', price: 18 },
    { name: '酸辣土豆丝饭', price: 16 },
    { name: '米饭(单点)', price: 3 },
  ]},
  { name: '蒸功夫', categoryId: 'rice', description: '现蒸现做，健康好味', tags: ['蒸品', '老牌'], deliveryFee: 4, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 4567, distanceKm: 1.2, rating: 4.3, items: [
    { name: '香菇滑鸡饭', subtitle: '蒸制', price: 25 },
    { name: '排骨饭', price: 28 },
    { name: '冬菇滑鸡饭', price: 25 },
    { name: '酸菜卤肉饭', price: 22 },
    { name: '鱼香茄子饭', price: 22 },
    { name: '鸡腿饭', price: 25 },
    { name: '牛肉饭', price: 28 },
    { name: '腊味煲仔饭', price: 30 },
    { name: '蒸蛋(加料)', price: 6 },
    { name: '例汤', price: 8 },
  ]},
  { name: '自选快餐', categoryId: 'rice', description: '自选称重快餐，品类丰富', tags: ['自选称重', '菜品丰富'], deliveryFee: 3, packingFee: 2, minOrder: 20, deliveryMin: 22, monthlySales: 5678, distanceKm: 0.8, rating: 4.4, items: [
    { name: '两荤一素套餐', price: 22 },
    { name: '一荤两素套餐', price: 18 },
    { name: '两荤两素套餐', price: 26 },
    { name: '红烧肉套餐', price: 25 },
    { name: '糖醋里脊套餐', price: 22 },
    { name: '回锅肉套餐', price: 22 },
    { name: '宫保鸡丁套餐', price: 20 },
    { name: '番茄鸡蛋套餐', price: 16 },
    { name: '米饭(单点)', price: 3 },
    { name: '例汤', price: 5 },
  ]},
  { name: '牛肉饭专门店', categoryId: 'rice', description: '日本牛肉饭专家', tags: ['日式', '牛肉饭'], deliveryFee: 5, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 3456, distanceKm: 1.5, rating: 4.4, items: [
    { name: '招牌牛肉饭(大)', subtitle: '日本配方', price: 35 },
    { name: '招牌牛肉饭(中)', price: 28 },
    { name: '照烧鸡腿饭', price: 28 },
    { name: '猪肉饭', price: 25 },
    { name: '咖喱牛肉饭', price: 30 },
    { name: '双拼饭(牛肉+鸡肉)', price: 35 },
    { name: '煎饺(6个)', price: 18 },
    { name: '味噌汤', price: 10 },
    { name: '茶碗蒸', price: 12 },
    { name: '土豆沙拉', price: 12 },
  ]},
  { name: '豆浆大王', categoryId: 'rice', description: '台湾风味中式快餐', tags: ['台湾风味', '豆浆'], deliveryFee: 4, packingFee: 2, minOrder: 20, deliveryMin: 25, monthlySales: 3210, distanceKm: 1.0, rating: 4.2, items: [
    { name: '卤肉饭', subtitle: '台式经典', price: 20 },
    { name: '宫保鸡丁饭', price: 22 },
    { name: '鱼香肉丝饭', price: 22 },
    { name: '红烧牛肉面', price: 28 },
    { name: '番茄鸡蛋面', price: 20 },
    { name: '油条(2根)', price: 6 },
    { name: '豆浆(热)', price: 8 },
    { name: '蛋饼', price: 10 },
    { name: '小笼包(6个)', price: 16 },
    { name: '煎饺(8个)', price: 18 },
  ]},
  { name: '川渝快餐', categoryId: 'rice', description: '西南中式快餐龙头', tags: ['川渝风味', '老牌'], deliveryFee: 4, packingFee: 2, minOrder: 22, deliveryMin: 25, monthlySales: 3890, distanceKm: 1.2, rating: 4.3, items: [
    { name: '铁板牛肉饭', price: 25 },
    { name: '泡椒鸡杂饭', subtitle: '川渝特色', price: 22 },
    { name: '回锅肉饭', price: 22 },
    { name: '鱼香肉丝饭', price: 20 },
    { name: '宫保鸡丁饭', price: 20 },
    { name: '干煸四季豆饭', price: 18 },
    { name: '番茄鸡蛋饭', price: 16 },
    { name: '红烧茄子饭', price: 18 },
    { name: '米饭(单点)', price: 3 },
    { name: '酸辣汤', price: 8 },
  ]},
  { name: '湘味蒸菜', categoryId: 'rice', description: '湖南浏阳特色蒸菜', tags: ['蒸菜', '湖南风味'], deliveryFee: 3, packingFee: 2, minOrder: 18, deliveryMin: 22, monthlySales: 2345, distanceKm: 0.8, rating: 4.4, items: [
    { name: '蒸腊肉饭', subtitle: '浏阳特色', price: 22 },
    { name: '蒸排骨饭', price: 22 },
    { name: '蒸鸡翅饭', price: 20 },
    { name: '蒸扣肉饭', price: 22 },
    { name: '蒸鱼头饭', price: 25 },
    { name: '蒸鸡蛋(加料)', price: 6 },
    { name: '蒸南瓜(加料)', price: 5 },
    { name: '蒸芋头(加料)', price: 5 },
    { name: '酸辣汤', price: 8 },
    { name: '米饭(单点)', price: 3 },
  ]},
  { name: '黄焖鸡米饭', categoryId: 'rice', description: '国民快餐，黄焖鸡专家', tags: ['国民快餐', '黄焖鸡'], deliveryFee: 3, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 4321, distanceKm: 0.5, rating: 4.1, items: [
    { name: '黄焖鸡(小份)', subtitle: '招牌', price: 18 },
    { name: '黄焖鸡(大份)', price: 25 },
    { name: '黄焖排骨(小份)', price: 20 },
    { name: '黄焖排骨(大份)', price: 28 },
    { name: '黄焖豆腐', price: 16 },
    { name: '黄焖肥肠', price: 22 },
    { name: '黄焖猪蹄', price: 28 },
    { name: '加料:土豆', price: 5 },
    { name: '加料:金针菇', price: 5 },
    { name: '米饭(单点)', price: 3 },
  ]},
  { name: '卤肉饭专门店', categoryId: 'rice', description: '一碗卤肉饭的极致', tags: ['卤肉饭', '专门店'], deliveryFee: 4, packingFee: 1, minOrder: 20, deliveryMin: 22, monthlySales: 2678, distanceKm: 1.0, rating: 4.5, items: [
    { name: '招牌卤肉饭', subtitle: '慢炖6小时', price: 22 },
    { name: '卤肉饭+卤蛋', price: 26 },
    { name: '卤肉饭+卤豆腐', price: 26 },
    { name: '卤肉饭+酸菜', price: 25 },
    { name: '大卤肉饭(加大)', price: 28 },
    { name: '卤蛋(2个)', price: 6 },
    { name: '卤豆腐', price: 5 },
    { name: '卤豆干', price: 5 },
    { name: '酸菜', price: 4 },
    { name: '味噌汤', price: 8 },
  ]},
  { name: '蒸菜小馆', categoryId: 'rice', description: '湘味蒸菜，健康家常', tags: ['蒸菜连锁', '健康'], deliveryFee: 4, packingFee: 2, minOrder: 22, deliveryMin: 25, monthlySales: 1987, distanceKm: 1.5, rating: 4.4, items: [
    { name: '腊味合蒸饭', subtitle: '招牌', price: 25 },
    { name: '剁椒鱼头饭', price: 28 },
    { name: '粉蒸肉饭', price: 22 },
    { name: '梅菜扣肉饭', price: 22 },
    { name: '蒸排骨饭', price: 22 },
    { name: '蒸鸡翅饭', price: 20 },
    { name: '蒸南瓜饭', price: 18 },
    { name: '蒸鸡蛋(加料)', price: 6 },
    { name: '蒸芋头(加料)', price: 5 },
    { name: '酸辣汤', price: 8 },
  ]},

  // ─────── 奶茶 (tea) ───────
  { name: '灵感茶铺', categoryId: 'tea', description: '现萃好茶，芝士奶盖香浓', tags: ['高端', '芝士茶'], deliveryFee: 5, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 5678, distanceKm: 1.5, rating: 4.7, items: [
    { name: '多肉葡萄', subtitle: '当季鲜葡萄', price: 28 },
    { name: '芝芝莓莓', price: 30 },
    { name: '多肉桃李', price: 25 },
    { name: '生打椰椰', price: 22 },
    { name: '烤黑糖波波', price: 20 },
    { name: '芝芝芒芒', price: 32 },
    { name: '纯茶(四季春)', price: 12 },
    { name: '纯茶(绿妍)', price: 12 },
    { name: '轻乳茶(伯爵)', price: 18 },
    { name: '冰淇淋(黑糖)', price: 15 },
  ]},
  { name: '甜筒茶饮', categoryId: 'tea', description: '高质平价，甜蜜好滋味', tags: ['平价之王', '全国最多'], deliveryFee: 2, packingFee: 1, minOrder: 8, deliveryMin: 18, monthlySales: 12345, distanceKm: 0.3, rating: 4.2, items: [
    { name: '冰鲜柠檬水', subtitle: '销量王', price: 4 },
    { name: '蜜桃四季春', price: 6 },
    { name: '珍珠奶茶', price: 6 },
    { name: '芋圆葡萄', price: 8 },
    { name: '杨枝甘露', price: 8 },
    { name: '棒打鲜橙', price: 6 },
    { name: '蜜桃乌龙茶', price: 6 },
    { name: '草莓啵啵', price: 8 },
    { name: '圣代(草莓)', price: 6 },
    { name: '圣代(芒果)', price: 6 },
  ]},
  { name: '百道茶铺', categoryId: 'tea', description: '新式茶饮，好喝不贵', tags: ['性价比高', '品类丰富'], deliveryFee: 4, packingFee: 1, minOrder: 15, deliveryMin: 22, monthlySales: 7890, distanceKm: 0.8, rating: 4.4, items: [
    { name: '杨枝甘露', subtitle: '招牌', price: 16 },
    { name: '超级杯水果茶', price: 18 },
    { name: '豆乳玉麒麟', price: 15 },
    { name: '西瓜啵啵', price: 14 },
    { name: '珍珠奶茶', price: 12 },
    { name: '芋泥波波', price: 16 },
    { name: '百香果茶', price: 12 },
    { name: '葡萄冰酿', price: 16 },
    { name: '芒果西米露', price: 15 },
    { name: '柠檬茶', price: 10 },
  ]},
  { name: '鲜果茶铺', categoryId: 'tea', description: '鲜果茶专家', tags: ['鲜果茶', '下沉之王'], deliveryFee: 3, packingFee: 1, minOrder: 12, deliveryMin: 20, monthlySales: 8901, distanceKm: 0.6, rating: 4.3, items: [
    { name: '超级杯柠檬茶', price: 12 },
    { name: '百香果茶', price: 12 },
    { name: '芝士莓莓', price: 18 },
    { name: '芝士葡萄', price: 18 },
    { name: '芋泥啵啵奶茶', price: 16 },
    { name: '珍珠奶茶', price: 10 },
    { name: '芒果西米露', price: 15 },
    { name: '杨枝甘露', price: 16 },
    { name: '蜜桃乌龙', price: 14 },
    { name: '西瓜啵啵', price: 12 },
  ]},
  { name: '国风茶姬', categoryId: 'tea', description: '东方茶韵，一杯知味', tags: ['国风', '鲜奶茶'], deliveryFee: 5, packingFee: 2, minOrder: 20, deliveryMin: 25, monthlySales: 6543, distanceKm: 1.2, rating: 4.6, items: [
    { name: '伯牙绝弦', subtitle: '招牌鲜奶茶', price: 18 },
    { name: '万里木兰', price: 18 },
    { name: '花田乌龙', price: 18 },
    { name: '青青糯山', price: 16 },
    { name: '桂馥兰香', price: 18 },
    { name: '去云南·玫瑰普洱', price: 20 },
    { name: '白桃乌龙', price: 16 },
    { name: '茉莉雪芽', price: 16 },
    { name: '鲜奶茶(大红袍)', price: 20 },
    { name: '纯茶(铁观音)', price: 12 },
  ]},
  { name: '烧仙草小铺', categoryId: 'tea', description: '烧仙草品类开创者', tags: ['烧仙草', '半杯都是料'], deliveryFee: 3, packingFee: 1, minOrder: 12, deliveryMin: 20, monthlySales: 5432, distanceKm: 0.8, rating: 4.3, items: [
    { name: '烧仙草小铺', subtitle: '半杯都是料', price: 12 },
    { name: '芋圆烧仙草', price: 14 },
    { name: '珍珠奶茶', price: 10 },
    { name: '红豆奶茶', price: 10 },
    { name: '杨枝甘露', price: 15 },
    { name: '芒果西米露', price: 14 },
    { name: '草莓啵啵', price: 14 },
    { name: '百香果茶', price: 12 },
    { name: '柠檬茶', price: 8 },
    { name: '冰淇淋红茶', price: 12 },
  ]},
  { name: '五谷茶铺', categoryId: 'tea', description: '五谷现煮茶专家', tags: ['五谷茶', '现煮'], deliveryFee: 4, packingFee: 1, minOrder: 15, deliveryMin: 22, monthlySales: 4567, distanceKm: 1.0, rating: 4.3, items: [
    { name: '血糯米奶茶', subtitle: '招牌', price: 14 },
    { name: '芋圆奶茶', price: 14 },
    { name: '红豆奶茶', price: 12 },
    { name: '燕麦奶茶', price: 14 },
    { name: '五谷杂粮茶', price: 16 },
    { name: '杨枝甘露', price: 16 },
    { name: '水果茶', price: 15 },
    { name: '柠檬茶', price: 10 },
    { name: '芒果冰沙', price: 14 },
    { name: '珍珠奶茶', price: 10 },
  ]},
  { name: '手摇茶铺', categoryId: 'tea', description: '台湾手摇茶代表', tags: ['台湾', '手摇茶'], deliveryFee: 4, packingFee: 1, minOrder: 15, deliveryMin: 22, monthlySales: 4321, distanceKm: 1.0, rating: 4.4, items: [
    { name: '四季春茶', price: 10 },
    { name: '波霸奶茶', subtitle: '大颗珍珠', price: 14 },
    { name: '红茶玛奇朵', price: 16 },
    { name: '乌龙玛奇朵', price: 16 },
    { name: '冰淇淋红茶', price: 16 },
    { name: '柠檬梅子绿', price: 14 },
    { name: '蜂蜜绿茶', price: 12 },
    { name: '百香双重奏', price: 16 },
    { name: '抹茶拿铁', price: 18 },
    { name: '燕麦奶茶', price: 16 },
  ]},
  { name: '经典茶铺', categoryId: 'tea', description: '经典茶饮品牌', tags: ['经典', '稳定出品'], deliveryFee: 4, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 5678, distanceKm: 0.8, rating: 4.3, items: [
    { name: '百香双响炮', subtitle: '招牌', price: 16 },
    { name: '珍珠奶茶', price: 12 },
    { name: '布丁奶茶', price: 14 },
    { name: '芋圆奶茶', price: 14 },
    { name: '鲜芋牛奶', price: 18 },
    { name: '芒果酸奶', price: 18 },
    { name: '柠檬茶', price: 10 },
    { name: '铁观音奶茶', price: 16 },
    { name: '红茶拿铁', price: 16 },
    { name: '三兄弟奶茶', subtitle: '珍珠+布丁+仙草', price: 18 },
  ]},
  { name: '幸运咖啡', categoryId: 'tea', description: '专业咖啡品牌', tags: ['咖啡', '高频'], deliveryFee: 4, packingFee: 2, minOrder: 15, deliveryMin: 20, monthlySales: 9876, distanceKm: 0.5, rating: 4.4, items: [
    { name: '生椰拿铁', subtitle: '爆款', price: 18 },
    { name: '标准美式', price: 12 },
    { name: '加浓美式', price: 14 },
    { name: '拿铁', price: 16 },
    { name: '澳瑞白', price: 18 },
    { name: '焦糖玛奇朵', price: 18 },
    { name: '摩卡', price: 18 },
    { name: '椰云拿铁', price: 20 },
    { name: '橙C美式', price: 16 },
    { name: '冰吸生椰拿铁', price: 20 },
  ]},

  // ─────── 甜品 (dessert) ───────
  { name: '港式甜品屋', categoryId: 'dessert', description: '港式甜品经典品牌', tags: ['港式', '经典'], deliveryFee: 6, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 2345, distanceKm: 2.0, rating: 4.6, items: [
    { name: '杨枝甘露', subtitle: '招牌', price: 38 },
    { name: '白雪黑珍珠', price: 32 },
    { name: '芒果班戟(2个)', price: 35 },
    { name: '榴莲班戟(2个)', price: 45 },
    { name: '焗荔蓉西米布甸', price: 28 },
    { name: '冰火菠萝油', price: 22 },
    { name: '芒果糯米糍(3个)', price: 28 },
    { name: '双皮奶', price: 22 },
    { name: '姜汁撞奶', price: 22 },
    { name: '龟苓膏', price: 20 },
  ]},
  { name: '芋圆甜品', categoryId: 'dessert', description: '台湾芋圆甜品专家', tags: ['台湾', '芋圆'], deliveryFee: 5, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 2678, distanceKm: 1.5, rating: 4.5, items: [
    { name: '芋圆甜品招牌', subtitle: '芋圆+仙草', price: 22 },
    { name: '芋圆1号', price: 20 },
    { name: '仙草1号', price: 20 },
    { name: '芋圆牛奶冰', price: 25 },
    { name: '芒果冰', price: 28 },
    { name: '红豆牛奶冰', price: 22 },
    { name: '芋头牛奶', price: 20 },
    { name: '芋泥波波', price: 22 },
    { name: '珍珠奶茶', price: 15 },
    { name: '紫薯圆牛奶冰', price: 25 },
  ]},
  { name: '暴风雪冰品', categoryId: 'dessert', description: '暴风雪冰淇淋', tags: ['冰淇淋', '暴风雪'], deliveryFee: 6, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 3456, distanceKm: 1.8, rating: 4.4, items: [
    { name: '暴风雪(奥利奥)', subtitle: '倒杯不洒', price: 28 },
    { name: '暴风雪(抹茶)', price: 28 },
    { name: '暴风雪(草莓)', price: 28 },
    { name: '暴风雪(巧克力)', price: 28 },
    { name: '软圆甜筒', price: 12 },
    { name: '华夫甜筒', price: 15 },
    { name: '圣代(草莓)', price: 18 },
    { name: '圣代(巧克力)', price: 18 },
    { name: '奶昔(香草)', price: 22 },
    { name: '蛋糕冰淇淋(小)', price: 68 },
  ]},
  { name: '面包蛋糕坊', categoryId: 'dessert', description: '咖啡·蛋糕·面包', tags: ['面包蛋糕', '台湾'], deliveryFee: 5, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 3890, distanceKm: 1.0, rating: 4.3, items: [
    { name: '海岩咖啡', price: 18 },
    { name: '珍珠奶茶', price: 12 },
    { name: '凯撒大帝面包', price: 12 },
    { name: '菠萝面包', price: 8 },
    { name: '抹茶红豆蛋糕(切块)', price: 18 },
    { name: '提拉米苏(切块)', price: 22 },
    { name: '芝士蛋糕(切块)', price: 22 },
    { name: '黑森林蛋糕(切块)', price: 20 },
    { name: '泡芙(2个)', price: 15 },
    { name: '蛋挞(3个)', price: 15 },
  ]},
  { name: '烘焙工坊', categoryId: 'dessert', description: '中国知名烘焙品牌', tags: ['烘焙', '半熟芝士'], deliveryFee: 5, packingFee: 2, minOrder: 30, deliveryMin: 30, monthlySales: 4567, distanceKm: 1.2, rating: 4.5, items: [
    { name: '半熟芝士(5枚装)', subtitle: '爆款', price: 38 },
    { name: '巧克力冰山(切块)', price: 25 },
    { name: '提拉米苏(切块)', price: 25 },
    { name: '原味吐司', price: 18 },
    { name: '北海道吐司', price: 22 },
    { name: '抹茶红豆卷', price: 15 },
    { name: '肉松小贝(4个)', price: 22 },
    { name: '泡芙(4个)', price: 20 },
    { name: '蛋挞(4个)', price: 20 },
    { name: '蝴蝶酥', price: 18 },
  ]},
  { name: '肉松糕点铺', categoryId: 'dessert', description: '肉松小贝排队王', tags: ['糕点', '排队王'], deliveryFee: 4, packingFee: 2, minOrder: 20, deliveryMin: 25, monthlySales: 3210, distanceKm: 1.5, rating: 4.6, items: [
    { name: '海苔肉松小贝(6个)', subtitle: '招牌', price: 28 },
    { name: '蟹黄肉松小贝(6个)', price: 30 },
    { name: '柠檬肉松小贝(6个)', price: 28 },
    { name: '奶香提子酥(盒)', price: 22 },
    { name: '蛋黄酥(4个)', price: 25 },
    { name: '凤梨酥(6个)', price: 22 },
    { name: '绿豆糕(盒)', price: 20 },
    { name: '雪花酥(盒)', price: 22 },
    { name: '牛轧糖(盒)', price: 25 },
    { name: '曲奇(盒)', price: 28 },
  ]},
  { name: '芒果甜品屋', categoryId: 'dessert', description: '港式芒果甜品专家', tags: ['芒果甜品', '港式'], deliveryFee: 6, packingFee: 2, minOrder: 30, deliveryMin: 28, monthlySales: 1876, distanceKm: 2.5, rating: 4.4, items: [
    { name: '芒果捞嘢', subtitle: '招牌', price: 35 },
    { name: '芒果西米捞', price: 30 },
    { name: '多芒小丸子', price: 28 },
    { name: '芒果班戟(2个)', price: 35 },
    { name: '双皮奶', price: 22 },
    { name: '杨枝甘露', price: 35 },
    { name: '椰汁西米糕', price: 25 },
    { name: '龟苓膏', price: 20 },
    { name: '姜汁撞奶', price: 22 },
    { name: '芒果糯米糍(3个)', price: 28 },
  ]},
  { name: '日式甜品屋', categoryId: 'dessert', description: '日式精致甜品', tags: ['日式', '精致'], deliveryFee: 6, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 1234, distanceKm: 2.8, rating: 4.5, items: [
    { name: '抹茶千层蛋糕(切块)', price: 32 },
    { name: '抹茶冰淇淋', price: 22 },
    { name: '红豆抹茶芭菲', price: 35 },
    { name: '焦糖布丁', price: 18 },
    { name: '草莓大福(3个)', price: 25 },
    { name: '铜锣烧(2个)', price: 18 },
    { name: '麻糬(3个)', price: 20 },
    { name: '抹茶拿铁', price: 22 },
    { name: '芝士蛋糕', price: 28 },
    { name: '泡芙(2个)', price: 20 },
  ]},
  { name: '现做蛋糕坊', categoryId: 'dessert', description: '新鲜现做蛋糕配送', tags: ['生日蛋糕', '配送'], deliveryFee: 0, packingFee: 3, minOrder: 60, deliveryMin: 60, monthlySales: 2890, distanceKm: 3.0, rating: 4.4, items: [
    { name: '水果蛋糕(6寸)', price: 128 },
    { name: '巧克力蛋糕(6寸)', price: 138 },
    { name: '芝士蛋糕(6寸)', price: 148 },
    { name: '抹茶蛋糕(6寸)', price: 138 },
    { name: '提拉米苏(6寸)', price: 158 },
    { name: '榴莲蛋糕(6寸)', price: 168 },
    { name: '千层蛋糕(6寸)', price: 158 },
    { name: '慕斯蛋糕(切块)', price: 28 },
    { name: '泡芙(4个)', price: 25 },
    { name: '蛋挞(4个)', price: 22 },
  ]},
  { name: '甜品盒子', categoryId: 'dessert', description: '网红甜品集合店', tags: ['网红', '颜值高'], deliveryFee: 5, packingFee: 2, minOrder: 25, deliveryMin: 25, monthlySales: 2345, distanceKm: 1.5, rating: 4.5, items: [
    { name: '脏脏包(2个)', subtitle: '巧克力爆浆', price: 22 },
    { name: '盒子蛋糕(草莓)', price: 28 },
    { name: '盒子蛋糕(芒果)', price: 28 },
    { name: '雪媚娘(3个)', price: 25 },
    { name: '毛巾卷(抹茶)', price: 25 },
    { name: '毛巾卷(可可)', price: 25 },
    { name: '泡芙(4个)', price: 22 },
    { name: '麻薯(6个)', price: 20 },
    { name: '提拉米苏杯', price: 28 },
    { name: '杨枝甘露杯', price: 25 },
  ]},

  // ─────── 夜宵 (night) ───────
  { name: '贴心火锅', categoryId: 'night', description: '极致服务的火锅体验', tags: ['火锅', '服务好'], deliveryFee: 8, packingFee: 3, minOrder: 80, deliveryMin: 45, monthlySales: 6789, distanceKm: 2.0, rating: 4.7, items: [
    { name: '番茄锅底', price: 38 },
    { name: '牛油麻辣锅底', price: 48 },
    { name: '菌汤锅底', price: 38 },
    { name: '捞派牛肉(200g)', price: 52 },
    { name: '捞派毛肚(200g)', price: 48 },
    { name: '虾滑(1份)', price: 42 },
    { name: '捞派黄喉', price: 32 },
    { name: '捞派鸭肠', price: 28 },
    { name: '手工面', price: 12 },
    { name: '番茄牛肉饭', price: 28 },
  ]},
  { name: '蓉城火锅', categoryId: 'night', description: '成都老火锅，麻辣鲜香', tags: ['成都火锅', '麻辣'], deliveryFee: 8, packingFee: 3, minOrder: 60, deliveryMin: 40, monthlySales: 4567, distanceKm: 2.5, rating: 4.5, items: [
    { name: '牛油红锅锅底', subtitle: '老成都', price: 52 },
    { name: '番茄锅底', price: 38 },
    { name: '鲜毛肚', price: 42 },
    { name: '精品肥牛', price: 48 },
    { name: '鹅肠', price: 32 },
    { name: '黄喉', price: 28 },
    { name: '麻辣牛肉', price: 38 },
    { name: '小郡肝', price: 28 },
    { name: '冰粉', price: 12 },
    { name: '红糖糍粑', price: 18 },
  ]},
  { name: '一人火锅', categoryId: 'night', description: '一人一锅的小火锅', tags: ['小火锅', '一人食'], deliveryFee: 5, packingFee: 2, minOrder: 35, deliveryMin: 30, monthlySales: 5432, distanceKm: 1.2, rating: 4.3, items: [
    { name: '精品肥牛套餐', subtitle: '含蔬菜拼盘', price: 42 },
    { name: '鲜蔬套餐', price: 32 },
    { name: '羊肉套餐', price: 38 },
    { name: '虾滑', price: 28 },
    { name: '手切鲜牛肉', price: 45 },
    { name: '午餐肉', price: 18 },
    { name: '冻豆腐', price: 10 },
    { name: '宽粉', price: 8 },
    { name: '麻酱(蘸料)', price: 5 },
    { name: '酸梅汤', price: 8 },
  ]},
  { name: '鸭血火锅馆', categoryId: 'night', description: '鸭血火锅开创者', tags: ['鸭血火锅', '成都味'], deliveryFee: 8, packingFee: 3, minOrder: 60, deliveryMin: 40, monthlySales: 3456, distanceKm: 2.8, rating: 4.5, items: [
    { name: '红汤锅底', price: 48 },
    { name: '招牌鸭血', subtitle: '必点', price: 22 },
    { name: '鲜毛肚', price: 42 },
    { name: '千层肚', price: 35 },
    { name: '精品肥牛', price: 48 },
    { name: '鹅肠', price: 32 },
    { name: '麻辣牛肉', price: 38 },
    { name: '小酥肉', price: 28 },
    { name: '冰粉', price: 12 },
    { name: '红糖糍粑', price: 18 },
  ]},
  { name: '冒菜西施', categoryId: 'night', description: '一个人的火锅', tags: ['冒菜', '一人食'], deliveryFee: 3, packingFee: 2, minOrder: 20, deliveryMin: 22, monthlySales: 4321, distanceKm: 0.8, rating: 4.2, items: [
    { name: '冒菜(荤素搭配500g)', price: 28 },
    { name: '冒菜(纯素300g)', price: 18 },
    { name: '冒菜(纯荤300g)', price: 35 },
    { name: '冒粉', price: 15 },
    { name: '冒面', price: 15 },
    { name: '午餐肉(加料)', price: 8 },
    { name: '鹌鹑蛋(加料)', price: 5 },
    { name: '豆皮(加料)', price: 5 },
    { name: '金针菇(加料)', price: 5 },
    { name: '宽粉(加料)', price: 6 },
  ]},
  { name: '鸭脖卤味', categoryId: 'night', description: '卤味零食专家', tags: ['卤味', '零食'], deliveryFee: 3, packingFee: 1, minOrder: 15, deliveryMin: 20, monthlySales: 6789, distanceKm: 0.5, rating: 4.2, items: [
    { name: '招牌鸭脖(大份)', price: 32 },
    { name: '招牌鸭脖(小份)', price: 20 },
    { name: '鸭锁骨', price: 22 },
    { name: '鸭翅', price: 18 },
    { name: '鸭掌', price: 22 },
    { name: '鸭肠', price: 18 },
    { name: '鸭头(2个)', price: 18 },
    { name: '毛豆', price: 12 },
    { name: '藕片', price: 12 },
    { name: '豆干', price: 12 },
  ]},
  { name: '甜辣鸭脖', categoryId: 'night', description: '甜辣鸭脖，锁鲜装', tags: ['甜辣', '锁鲜装'], deliveryFee: 4, packingFee: 1, minOrder: 20, deliveryMin: 22, monthlySales: 5678, distanceKm: 0.8, rating: 4.3, items: [
    { name: '鸭脖(锁鲜装)', subtitle: '招牌甜辣', price: 28 },
    { name: '鸭锁骨(锁鲜装)', price: 25 },
    { name: '鸭翅(锁鲜装)', price: 22 },
    { name: '鸭掌(锁鲜装)', price: 25 },
    { name: '鸭肠(锁鲜装)', price: 22 },
    { name: '鸭舌(锁鲜装)', price: 35 },
    { name: '鸭头(2个)', price: 20 },
    { name: '卤藕片', price: 15 },
    { name: '卤毛豆', price: 12 },
    { name: '卤豆干', price: 12 },
  ]},
  { name: '深夜烤鱼', categoryId: 'night', description: '深夜烤鱼+小串', tags: ['深夜食堂', '烤鱼'], deliveryFee: 5, packingFee: 2, minOrder: 40, deliveryMin: 35, monthlySales: 2345, distanceKm: 1.5, rating: 4.4, items: [
    { name: '麻辣烤鱼(2.5斤)', subtitle: '深夜招牌', price: 118 },
    { name: '蒜香烤鱼(2.5斤)', price: 118 },
    { name: '豆豉烤鱼(2.5斤)', price: 108 },
    { name: '烤茄子', price: 18 },
    { name: '锡纸金针菇', price: 15 },
    { name: '炸酥肉', price: 25 },
    { name: '卤鸡爪(6只)', price: 28 },
    { name: '凉拌毛豆', price: 12 },
    { name: '冰粉', price: 10 },
    { name: '酸梅汤', price: 8 },
  ]},
  { name: '佐餐卤鸡', categoryId: 'night', description: '佐餐卤味专家', tags: ['佐餐卤味', '家庭装'], deliveryFee: 3, packingFee: 1, minOrder: 20, deliveryMin: 20, monthlySales: 4567, distanceKm: 0.6, rating: 4.3, items: [
    { name: '百味鸡(半只)', subtitle: '招牌', price: 42 },
    { name: '夫妻肺片(200g)', price: 28 },
    { name: '藤椒鸡(200g)', price: 25 },
    { name: '麻辣鸭脖(大份)', price: 28 },
    { name: '鸭翅(200g)', price: 22 },
    { name: '猪蹄(半只)', price: 35 },
    { name: '卤牛肉(200g)', price: 42 },
    { name: '毛豆', price: 12 },
    { name: '花生米', price: 10 },
    { name: '卤豆干', price: 12 },
  ]},
  { name: '成都串串香', categoryId: 'night', description: '成都串串香代表', tags: ['串串香', '成都'], deliveryFee: 6, packingFee: 2, minOrder: 40, deliveryMin: 35, monthlySales: 3456, distanceKm: 2.0, rating: 4.5, items: [
    { name: '红汤锅底', price: 38 },
    { name: '小郡肝(30串)', subtitle: '招牌', price: 45 },
    { name: '牛肉串(20串)', price: 50 },
    { name: '毛肚(10串)', price: 35 },
    { name: '鸭肠(10串)', price: 28 },
    { name: '藕片(10串)', price: 15 },
    { name: '土豆片(10串)', price: 12 },
    { name: '豆皮(10串)', price: 12 },
    { name: '冰粉', price: 10 },
    { name: '红糖糍粑', price: 18 },
  ]},
];

/* ═══════════════════════════════════════════════
   Build & Export
   ═══════════════════════════════════════════════ */
export const stores: StoreDetail[] = [
  ...choutuanStores,
  japaneseBuffetStore,
  kamiiBuffetStore,
];
